name: Deploy CDK App
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: AWS Demo Environment
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            
            - name: Check AWS_ACCESS_KEY_ID
              run: |
                  if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
                    echo "AWS_ACCESS_KEY_ID is not set."
                  else
                    echo "AWS_ACCESS_KEY_ID is set."
                  fi
        
            - name: Check AWS_SECRET_ACCESS_KEY
              run: |
                  if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
                    echo "AWS_SECRET_ACCESS_KEY is not set."
                  else
                    echo "AWS_SECRET_ACCESS_KEY is set."
                  fi
        
            - name: Check AWS_DEFAULT_REGION
              run: |
                  if [ -z "${{ secrets.AWS_DEFAULT_REGION }}" ]; then
                    echo "AWS_DEFAULT_REGION is not set."
                  else
                    echo "AWS_DEFAULT_REGION is set."
                  fi
            
            - name: Install AWS CDK CLI
              run: npm install -g aws-cdk
            
            - name: Install TypeScript
              run: npm install -g typescript

            - name: Install dependencies
              run: npm install
            
            - name: Check AWS CLI and CDK versions
              run: |
                aws --version

            - name: Test AWS Credentials
              run: aws s3 ls
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            
            - name: Bootstrap CDK
              run: npx cdk bootstrap
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Deploy CDK Stack
              run: npx cdk deploy --require-approval never
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
